-- Upgrade: add custom profile columns to UNITS table
-- Run once against the target Snowflake database

ALTER TABLE UNITS ADD COLUMN IF NOT EXISTS CUSTOM_TUT_SIZE     FLOAT;
ALTER TABLE UNITS ADD COLUMN IF NOT EXISTS CUSTOM_LECT_HOURS   FLOAT;
ALTER TABLE UNITS ADD COLUMN IF NOT EXISTS CUSTOM_TUT_HOURS    FLOAT;
ALTER TABLE UNITS ADD COLUMN IF NOT EXISTS CUSTOM_PREP_HOURS   FLOAT;
ALTER TABLE UNITS ADD COLUMN IF NOT EXISTS CUSTOM_ADMIN_HOURS  FLOAT;
ALTER TABLE UNITS ADD COLUMN IF NOT EXISTS CUSTOM_STUDENT_HOURS FLOAT;
