-- Upgrade: add FEE_TYPE_TABLE and FEE_TYPE_COLUMN columns to MODEL_CONFIG
-- Run once against the target Snowflake database

ALTER TABLE MODEL_CONFIG ADD COLUMN IF NOT EXISTS FEE_TYPE_TABLE VARCHAR;
ALTER TABLE MODEL_CONFIG ADD COLUMN IF NOT EXISTS FEE_TYPE_COLUMN VARCHAR;

-- Backfill existing rows with the previous hard-coded defaults
UPDATE MODEL_CONFIG SET FEE_TYPE_TABLE = 'COURSES_OBJECTS' WHERE FEE_TYPE_TABLE IS NULL;
UPDATE MODEL_CONFIG SET FEE_TYPE_COLUMN = 'COURSE_FEE_TYPE' WHERE FEE_TYPE_COLUMN IS NULL;
