-- Upgrade: add dimension structure columns to MODEL_CONFIG
-- Supports three fact table shapes:
--   GL3: GL -> Units -> Courses  (CODE1=GL, CODE2=Units, CODE3=Courses)
--   GL2: GL -> Courses direct    (CODE1=GL, CODE3=Courses, no unit view)
--   U2:  Units -> Courses        (CODE1=Units, CODE2=Courses, no GL join)
-- Run once against the target Snowflake database

ALTER TABLE MODEL_CONFIG ADD COLUMN IF NOT EXISTS COURSE_CODE_COL VARCHAR;
ALTER TABLE MODEL_CONFIG ADD COLUMN IF NOT EXISTS UNIT_CODE_COL VARCHAR;
ALTER TABLE MODEL_CONFIG ADD COLUMN IF NOT EXISTS UNIT_DIM_TABLE VARCHAR;
ALTER TABLE MODEL_CONFIG ADD COLUMN IF NOT EXISTS INCLUDE_GL_JOIN VARCHAR;
ALTER TABLE MODEL_CONFIG ADD COLUMN IF NOT EXISTS GL_CODE_COL VARCHAR;

-- Backfill existing rows with the GL3 defaults (original hard-coded behaviour)
UPDATE MODEL_CONFIG SET COURSE_CODE_COL = 'CODE3'          WHERE COURSE_CODE_COL IS NULL;
UPDATE MODEL_CONFIG SET UNIT_CODE_COL   = 'CODE2'          WHERE UNIT_CODE_COL   IS NULL;
UPDATE MODEL_CONFIG SET UNIT_DIM_TABLE  = 'PRODUCTS_OBJECTS' WHERE UNIT_DIM_TABLE  IS NULL;
UPDATE MODEL_CONFIG SET INCLUDE_GL_JOIN = 'TRUE'           WHERE INCLUDE_GL_JOIN IS NULL;
UPDATE MODEL_CONFIG SET GL_CODE_COL     = 'CODE1'          WHERE GL_CODE_COL     IS NULL;
